apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compassconnections.compass.kyma-project.io
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "compass-runtime-agent"
    meta.helm.sh/release-namespace: "compass-system"
spec:
  group: compass.kyma-project.io
  version: v1alpha1
  names:
    kind: CompassConnection
    listKind: CompassConnectionList
    plural: compassconnections
    singular: compassconnection
  scope: Cluster