apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceinstances.servicecatalog.k8s.io
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    svcat: "true"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "service-catalog"
    meta.helm.sh/release-namespace: "kyma-system"
spec:
  group: servicecatalog.k8s.io
  versions:
  - name: v1beta1
    storage: true
    served: true
  scope: Namespaced
  names:
    plural: serviceinstances
    singular: serviceinstance
    kind: ServiceInstance
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  additionalPrinterColumns:
    - name: Class
      type: string
      JSONPath: .status.userSpecifiedClassName
    - name: Plan
      type: string
      JSONPath: .status.userSpecifiedPlanName
    - name: Status
      type: string
      JSONPath: .status.lastConditionState
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
