apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificaterequests.applicationconnector.kyma-project.io
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "application-connector"
    meta.helm.sh/release-namespace: "kyma-integration"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: applicationconnector.kyma-project.io
  version: v1alpha1
  names:
    kind: CertificateRequest
    singular: certificaterequest
    plural: certificaterequests
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            csrInfoUrl:
              type: string
          required:
          - csrInfoUrl
          type: object

