global:
  containerRegistry:
    path: eu.gcr.io/kyma-project
  controllerManager:
    name: controller-manager
    image: event-sources-controller-manager
    dir: ''
    version: PR-6745
  httpAdapter:
    image: event-sources-http-adapter
    dir: ''
    version: PR-6745
