global:
  containerRegistry:
    path: eu.gcr.io/kyma-project
  controllerManager:
    name: controller-manager
    image: event-sources-controller-manager
    dir: ''
    version: 4e608dfb
  httpAdapter:
    image: event-sources-http-adapter
    dir: ''
    version: 4e608dfb
  e2e_external_solution:
    dir: pr/
    version: PR-6684
  isLocalEnv: false

test:
  acceptance:
    external_solution:
      enabled: true
    application_connector_test:
      connector_service:
        central: false