{{- if not (.Capabilities.APIVersions.Has "servicecatalog.k8s.io/v1beta1/ClusterServiceClass") }}
{{- if .Release.IsUpgrade }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterserviceclasses.servicecatalog.k8s.io
  labels:
    svcat: "true"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  versions:
    - name: v1beta1
      storage: true
      served: true
  scope: Cluster
  names:
    plural: clusterserviceclasses
    singular: clusterserviceclass
    kind: ClusterServiceClass
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  additionalPrinterColumns:
    - name: External-Name
      type: string
      JSONPath: .spec.externalName
    - name: Broker
      type: string
      JSONPath: .spec.clusterServiceBrokerName
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}

{{- end }}
{{- end }}

