{{- if .Release.IsUpgrade }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceclasses.servicecatalog.k8s.io
  labels:
    svcat: "true"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  group: servicecatalog.k8s.io
  version: v1beta1
  versions:
  - name: v1beta1
    storage: true
    served: true
  scope: Namespaced
  names:
    plural: serviceclasses
    singular: serviceclass
    kind: ServiceClass
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
      - all
      - svcat
  additionalPrinterColumns:
    - name: External-Name
      type: string
      JSONPath: .spec.externalName
    - name: Broker
      type: string
      JSONPath: .spec.serviceBrokerName
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}

{{- end }}

