apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-remove-knative-serving
  annotations:
    helm.sh/hook: "pre-upgrade"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-remove-knative-serving
  annotations:
    helm.sh/hook: "pre-upgrade"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
      - rolebindings
    verbs:
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - serviceaccounts
      - configmaps
    verbs:
      - list
      - delete
      - get
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - list
      - delete
  - apiGroups:
      - "apiregistration.k8s.io"
    resources:
      - apiservices
    verbs:
      - list
      - delete
  - apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - delete
  - apiGroups:
      - "caching.internal.knative.dev"
    resources:
      - images
    verbs:
      - list
      - delete
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - list
      - delete
  - apiGroups:
      - "authentication.istio.io"
    resources:
      - policies
    verbs:
      - list
      - delete
  - apiGroups:
      - "monitoring.coreos.com"
    resources:
      - podmonitors
    verbs:
      - list
      - delete
  - apiGroups:
      - "networking.istio.io"
    resources:
      - destinationrules
    verbs:
      - list
      - delete
